---
application: "base"
schemaVersion: "applicationDescriptor/0.11.0"
description: ""
owner: "None"
sources:
- name: "cobol"
  repositoryPath: "src/cobol"
  language: "COBOL"
  languageProcessor: "Cobol.groovy"
  fileExtension: "cbl"
  artifactsType: "Program"
  files:
  - name: "BAB1"
    type: "UNKNOWN"
    usage: "main"
  - name: "BAM1"
    type: "UNKNOWN"
    usage: "main"
  - name: "BAO1"
    type: "UNKNOWN"
    usage: "main"
- name: "copy"
  repositoryPath: "src/copy"
  language: "COBOL"
  languageProcessor: "none"
  fileExtension: "cpy"
  artifactsType: "Include File"
  files:
  - name: "BAD1REC"
    type: "UNKNOWN"
    usage: "public"
  - name: "BAD1SQL"
    type: "UNKNOWN"
    usage: "public"
  - name: "BAM1"
    type: "UNKNOWN"
    usage: "public"
baselines:
- branch: "main"
  type: "release"
  reference: "rel-1.0.0"
  buildid: "baseline"
- branch: "release/rel-1.0.0"
  type: "release"
  reference: "rel-1.0.0"
  buildid: "baseline"
consumers:
- name: "customer"
- name: "payment"
