apiVersion: deploy.ibm.com/v1
kind: DeploymentPlan
metadata:
  name: base
  description: base
  version: 20250617.094751.821
  annotations:
    creation_timestamp: 20250617.074754.979
    engine:
      version: 3.0.5
      build: manual
      date: Thu Apr 24 00:41:15 CEST 2025
    package:
      path: /u/dbehm/wazi-deploy/workspace/ts1_delete_base/base/main/dbbbuild_2025-06-17_09-46-25/logs/base-rel-1.0.0-2025-06-17_09-46-25_delete.tar
      sha256: 263877c580dd68719e730a85811c58736ba0ad09b2047d900274c00375f93a0e
activities:
- name: CONFIG
  description: |-
    Load the generic Wazi Deploy Configuration variables
    Specific for the Python implementation
  properties: []
  actions:
  - name: READ CONFIGURATION
    properties: []
    steps:
    - name: INCLUDE ENVIRONMENT VARIABLES
      properties:
      - key: template
        value: include_vars
      - key: var_include_vars
        value: include_environment_vars
      artifacts: []
      types: []
      short_name: INCLUDE_ENV_VARS
    - name: INCLUDE MIDDLEWARE VARIABLES
      properties:
      - key: template
        value: include_vars
      - key: var_include_vars
        value: include_middleware_vars
      artifacts: []
      types: []
      short_name: INCLUDE_MIDDLEWARE_VARS
    - name: INCLUDE GLOBAL VARIABLES
      properties:
      - key: template
        value: include_vars
      - key: var_include_vars
        value: include_common_vars
      artifacts: []
      types: []
      short_name: INCLUDE_GLOBAL_VARS
    types: []
    short_name: CONFIG
  types: []
- name: PACKAGE
  description: |-
    This activity expands the package into the working directory
  properties: []
  actions:
  - name: PACKAGE
    properties: []
    steps:
    - name: PACKAGE
      properties: []
      artifacts: []
      types: []
    types: []
  types: []
  tags:
  - package
- name: DELETE_MODULES
  description: |-
    This activity is dedicated to the deletion of the artifacts from the PDS(E)s
  properties: []
  actions:
  - name: DELETE
    description: |-
      This action is applicable when the artifacts are deleted
    properties: []
    steps:
    - name: MEMBER_ARCHIVE
      description: |-
        This step backs up already installed artifacts into the backup PDS
      properties: []
      artifacts:
      - name: BAB1
        properties:
        - key: path
          value: bin/jcl/BAB1.JCL
        - key: githash
          value: a1626e9622567a27932e3b36ad933e6bfb5302cf
        - key: giturl
          value: https://github.com/dennis-behm/base.git
        - key: wd_manifest_index
          value: 0
        - key: type
          value: JCL
        hash: a1626e9622567a27932e3b36ad933e6bfb5302cf
      types: []
    - name: MEMBER_DELETE
      description: |-
        This step deletes the artifacts
      properties: []
      artifacts:
      - name: BAB1
        properties:
        - key: path
          value: bin/jcl/BAB1.JCL
        - key: githash
          value: a1626e9622567a27932e3b36ad933e6bfb5302cf
        - key: giturl
          value: https://github.com/dennis-behm/base.git
        - key: wd_manifest_index
          value: 0
        - key: type
          value: JCL
        hash: a1626e9622567a27932e3b36ad933e6bfb5302cf
      types: []
    types: []
  is_artifact: true
  types:
  - name: DBRM
  - name: LOAD
  - name: CICSLOAD
  - name: MAPLOAD
  - name: JCL
manifests:
- name: base
  description: base
  version: 20250617.094751.821
  annotations:
    creationTimestamp: 20250617.094751.821
    scmInfo:
      type: git
      uri: https://github.com/dennis-behm/base.git
      branch: main
      shortCommit: a1626e9622567a27932e3b36ad933e6bfb5302cf
deployment_methods:
- apiVersion: deploy.ibm.com/v1
  kind: DeploymentMethod
  metadata:
    name: CICS
    description: |-
      This deployment method can be use for the deployment of an CICS application.
    version: 1.0.0
    annotations:
      deployVersion: 1.0.0
